***Q1.Swap two columns in a 2D array.***

In [1]:
import numpy as np

In [2]:
y = np.array([[1, 2],
              [4, 5],
              [7, 8]])

y[:,[0,1]] = y[:,[1,0]]
y

array([[2, 1],
       [5, 4],
       [8, 7]])

***Q2.Swap two rows in a 2D array.***

In [3]:
u = np.array([[1,2,3],
              [4,5,6]])

u[[0,1],:] = u[[0,1],:]
u

array([[1, 2, 3],
       [4, 5, 6]])

***Q3.Reverse all the rows of a 2D array.***

In [4]:
x = np.array([[3,2,1],
              [6,5,4]])

x[:,[0,1,2]] = x[:,[2,1,0]]
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
e = np.array([[3,2,1],
              [6,5,4]])

e = e[:,::-1]
e

array([[1, 2, 3],
       [4, 5, 6]])

***Q4.Extract all numbers between a given range from a one dimensional ndarray.***

In [6]:
y = np.array([1,3,2,55,7,3,63,63,6,3,5,5,4])           
y = np.array([i for i in y if 4<=i<=10])
y

array([7, 6, 5, 5, 4])

In [7]:
y = np.array([1,3,2,55,7,3,63,63,6,3,5,5,4]) 
lst = []
for i in y:
    if 4<=i<=10:
        lst.append(i)
lst    

[7, 6, 5, 5, 4]

In [8]:
# Method 2
t = np.array([1,2,34,5,22,6,78,3,78,4])
t[(t >= 2) * (t <= 6)]

array([2, 5, 6, 3, 4])

In [9]:
t[t>=4]

array([34,  5, 22,  6, 78, 78,  4])

In [10]:
t>=4

array([False, False,  True,  True,  True,  True,  True, False,  True,
        True])

***Q5.Given a list of words, find the words with atleast 2 vowels.***

In [11]:
lst = ["Hello","World","Python","Data Science"]
vowels_words = []
for x in lst:
    count = 0
    for i in x:
        if i in "aeiouAEIOU":
            count = count + 1        # count +=1
    if count>=2:
        vowels_words.append(x)

In [12]:
vowels_words

['Hello', 'Data Science']