# How To Create An Array.

In [ ]:
# importing numpy
import numpy as np
arr = np.array([1,2,3,4,5])         # Creating an ndarray
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array({1,2,3,4,5})
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
arr = np.array({1:"str",2:"hello"})
arr

array({1: 'str', 2: 'hello'}, dtype=object)

In [ ]:
x = np.array(["str","hello","world"])
x

array(['str', 'hello', 'world'], dtype='<U5')

In [ ]:
# Creating a zero-dimensional array
import numpy as np
arr = np.array("60")
print(arr)

60


In [ ]:
# Creating a one-dimensional array
# Each value in a 1D array is 0d array
import numpy as np
arr = np.array ([10,20,30,40])
print(arr)

[10 20 30 40]


In [ ]:
# creating a 2d array
# it has 1d array as its elements.
import numpy as np
arr = np.array ([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Creating a 3d array
# it has 2D array as its elements.
import numpy as np
arr = np.array ([([1,2,3,4],[5,6,7,8]),([1,2,3,4],[5,6,7,8]),([1,2,3,4],[5,6,7,8])])

print(arr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
# Creating a 4d array
# it has 3d array ad its elements.
import numpy as np
arr = np.array ([[([1,2,3,4],[5,6,7,8]),([1,2,3,4],[5,6,7,8]),([1,2,3,4],[5,6,7,8]),([1,2,3,4],[5,6,7,8])]])

print(arr)

[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]]


In [ ]:
np.array([[[1,2],[3,4],
           [5,6],[6,7]],
          [[4,5],[5,6],
           [6,7],[7,8]]])

array([[[1, 2],
        [3, 4],
        [5, 6],
        [6, 7]],

       [[4, 5],
        [5, 6],
        [6, 7],
        [7, 8]]])

In [ ]:
# what could be the another way to create an array.
y = [1,2,3,4]
x = np.array(y)
x

array([1, 2, 3, 4])

In [ ]:
# what could be the another way to create an array.
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.ndim

1

In [ ]:
# the game is all about Square brackets.
# it will tell u the dimension on the basis of bracket.
ar1 = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
ar1.ndim

32

In [ ]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%timeit my_arr2 = my_arr * 2

456 µs ± 119 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_list2 = [x*2 for x in my_list]

48.9 ms ± 11.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
x = np.array(["str","hello","world"])
x

array(['str', 'hello', 'world'], dtype='<U5')

In [ ]:
x = np.array(["str",23,45.7,78j])
x

array(['str', '23', '45.7', '78j'], dtype='<U64')

In [ ]:
x = np.array([None])
x

array([None], dtype=object)

In [ ]:
x = np.array([True,False])
x

array([ True, False])

# Data Types In NumPy.

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,-78],dtype="object")
x,x.dtype

(array([1, 2, 3, -78], dtype=object), dtype('O'))

In [ ]:
x = np.array([1,2,3,56],dtype="U")
x,x.dtype

(array(['1', '2', '3', '56'], dtype='<U2'), dtype('<U2'))

In [ ]:
x = np.array([1,2,3,-78],dtype="S")
x,x.dtype

(array([b'1', b'2', b'3', b'-78'], dtype='|S3'), dtype('S3'))

In [ ]:
x = np.array([1,2,3,"str"],dtype="object")
x,x.dtype

(array([1, 2, 3, 'str'], dtype=object), dtype('O'))

In [ ]:
x = np.array([1,2,3,56435555555555555555554566784266],dtype="int32")
x,x.dtype

OverflowError: ignored

In [ ]:
y = np.array(["hello","world","dog","cat"],dtype="S")
y,y.dtype

(array([b'hello', b'world', b'dog', b'cat'], dtype='|S5'), dtype('S5'))

In [ ]:
x = np.array(["hello hi","world","deg"])
x

array(['hello hi', 'world', 'deg'], dtype='<U8')

In [ ]:
len("hello hi")

8

# NumPy Array Inspection.

In [ ]:
import numpy as np

In [ ]:
# ndarray.ndim  - Returns the no.of dimensions.
x = np.array([[[[1,2],[4,5],[2,3],[5,6]]]])
x.ndim

4

In [ ]:
x

array([[[[1, 2],
         [4, 5],
         [2, 3],
         [5, 6]]]])

In [ ]:
# ndarray.shape  - Returns the Shape.
x.shape

(1, 1, 4, 2)

In [ ]:
# ndarray.ndim  - Returns the no.of dimensions.
x = np.array([[[[[1,2],[4,5],[2,3],[5,6]]]]])
x.ndim

5

In [ ]:
x.shape

(1, 1, 1, 4, 2)

In [ ]:
x = np.array([[[1,2,4],[4,5,6],[2,3,3],[5,6,2],[1,2,4],[4,5,6],[2,3,3],[5,6,2],[1,2,4],[4,5,6],[2,3,3],[5,6,2]]])
x.ndim

3

In [ ]:
x.shape

(1, 12, 3)

In [ ]:
s = np.array([[[[3,4,5,6],
                [4,5,6,7],
                [4,2,5,8],
                [2,3,4,5]],

               [[4,6,7,8],
                [5,6,7,8],
                [6,5,7,8],
                [2,5,74,89]],

               [[4,6,7,8],
                [5,6,7,8],
                [6,5,7,8],
                [2,5,74,89]]]])
print(s)

[[[[ 3  4  5  6]
   [ 4  5  6  7]
   [ 4  2  5  8]
   [ 2  3  4  5]]

  [[ 4  6  7  8]
   [ 5  6  7  8]
   [ 6  5  7  8]
   [ 2  5 74 89]]

  [[ 4  6  7  8]
   [ 5  6  7  8]
   [ 6  5  7  8]
   [ 2  5 74 89]]]]


In [ ]:
s.shape

(1, 3, 4, 4)

In [ ]:
x = np.array([[[[3,4,5],
                [4,5,6]],
               [[4,2,5],
                [2,3,4]]],

              [[[4,6,7],
                [5,6,7]],
               [[6,5,7],
                [2,5,74]]]])

print(x)

[[[[ 3  4  5]
   [ 4  5  6]]

  [[ 4  2  5]
   [ 2  3  4]]]


 [[[ 4  6  7]
   [ 5  6  7]]

  [[ 6  5  7]
   [ 2  5 74]]]]


In [ ]:
x.shape

(2, 2, 2, 3)

In [ ]:
# Work.
(1,2,1,4)
(3,2,1,4)
(2,3,5)
(1,2,3,5)

In [ ]:
s = np.array([[[1,2,3,4,5],
               [6,7,8,9,6],
               [1,2,3,4,5]],

              [[4,5,6,7,8],
               [8,3,6,2,5],
               [3,4,2,5,8]]])
print(s)

[[[1 2 3 4 5]
  [6 7 8 9 6]
  [1 2 3 4 5]]

 [[4 5 6 7 8]
  [8 3 6 2 5]
  [3 4 2 5 8]]]


In [ ]:
s.shape

(2, 3, 5)

In [ ]:
(1,2,3,5)

v = np.array([[[[5,6,3,4,5],
                [3,4,5,6,7],
                [6,7,8,9,5]],

               [[5,6,3,4,5],
                [3,4,5,6,7],
                [6,7,8,9,5]]]])

In [ ]:
v.shape

(1, 2, 3, 5)

In [ ]:
(1,2,1,4)

f = np.array([[[[5,6,3,4]],
               [[5,6,3,4]]]])
print(f)

[[[[5 6 3 4]]

  [[5 6 3 4]]]]


In [ ]:
f.shape

(1, 2, 1, 4)

In [ ]:
(3,2,1,4)
t = np.array([[[[3,4,5,6]],
               [[3,4,5,6]]],

              [[[3,4,5,6]],
               [[3,4,5,6]]],

              [[[3,4,5,6]],
               [[3,4,5,6]]]])
print(t)

[[[[3 4 5 6]]

  [[3 4 5 6]]]


 [[[3 4 5 6]]

  [[3 4 5 6]]]


 [[[3 4 5 6]]

  [[3 4 5 6]]]]


In [ ]:
t.shape

(3, 2, 1, 4)

In [ ]:
# change the shape of an array.
# shape of an ndarray also gives its size and no. of dimensions.
# for size, multiply the values in the shape tuple . e.g.(2,3) ---- 2*3=6
#for dimensions ,count the no.of values in the shape tuple e.g (2,3) --2Dimensional.
# while changing the shape of an array keep in mind that its size will not change.
import numpy as np
x = np.array([1,2,3,4])
print(x.shape)
print(x)
# (2,2) ==2*2 = 4
# (2*3) ==2*3 = 6
x.shape = (1,1,2,2)  # 1*2*2 = 4
x

(4,)
[1 2 3 4]


array([[[[1, 2],
         [3, 4]]]])

In [ ]:
# (4,4)
y = np.array([2,5,6,3,6,3,5,7])
print(y.shape)
print(y)

(8,)
[2 5 6 3 6 3 5 7]


In [ ]:
y.shape = (1,8)
y

array([[2, 5, 6, 3, 6, 3, 5, 7]])

In [ ]:
y.shape = (1,4,2)
y

array([[[2, 5],
        [6, 3],
        [6, 3],
        [5, 7]]])

In [ ]:
y.shape = (1,2,2,2)
y

array([[[[2, 5],
         [6, 3]],

        [[6, 3],
         [5, 7]]]])

In [ ]:
y.shape = (1,1,2,2,2)
y

array([[[[[2, 5],
          [6, 3]],

         [[6, 3],
          [5, 7]]]]])

In [ ]:
# ndarray.size - Returns the no. of elements.
x = np.array([1,2,3,4,5])
x.size

5

In [ ]:
# ndarray.dtype - Returns the dtype of the elements in the ndarray.
x.dtype

dtype('int64')

# Methods and Function used with ndarrays.

In [ ]:
import numpy as np

In [ ]:
# np.ones(shape,dtype) - Returns a new array of given shape and type, filled with ones.
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((1,5),"int32")

array([[1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
# np.zeros(shape,dtype) - Returns a new array of given shape and type, filled with zeros.
np.zeros((1,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
np.zeros((0,6),"int64")

array([], shape=(0, 6), dtype=int64)

In [ ]:
# np.empty(shape,dtype)
# Return a new array of given shape and type, without initializing entries.
np.empty((2,1),"uint")

array([[94640398406234],
       [             0]], dtype=uint64)

In [ ]:
np.empty((2,1),"U")

array([[''],
       ['']], dtype='<U1')

In [ ]:
np.empty((2,1),"S")

array([[b'\x19'],
       [b'\x14']], dtype='|S1')

In [ ]:
np.empty((2,1),"O")

array([[None],
       [None]], dtype=object)

In [ ]:
# np.full(shape,fill_value,dtype) -
# Returns the new array of given shape and type, filled with fill_value.
x = (2,1,4,5)
y = 10
np.full(x,y)

array([[[[10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10]]],


       [[[10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10]]]])

In [ ]:
np.full(x,y).dtype

dtype('int64')

In [ ]:
y = np.array([1,5])
y.dtype

dtype('int64')

In [ ]:
np.array([1,4]).dtype   ######

dtype('int64')

In [ ]:
# np.arange(start,stop,step,dtype) - Returns evenly spaced values within a given interval.
np.arange(3,10,2)

array([3, 5, 7, 9])

In [ ]:
# can we use floating point start ,stop & step.
# yes, we can also use floating point number in arange.
np.arange(3.5,11.7,2.4)

array([ 3.5,  5.9,  8.3, 10.7])

In [ ]:
np.arange(3.5,1.1,2.4).dtype

dtype('float64')

In [ ]:
# numpy.linspace(start,stop,num=50,endpoint=True,dtype)
# Return evenly spaced numbers over a specified interval.
# what do num=50 and endpoint+true suggest here?
# num=50 is the default value of num whhen not given ,i.e. , it will give 50 numbers in the range.
# endpoint+True is the default value of endpoint which tells us that he stop value is inclusive by default.
np.linspace(2,10,endpoint=False)

array([2.  , 2.16, 2.32, 2.48, 2.64, 2.8 , 2.96, 3.12, 3.28, 3.44, 3.6 ,
       3.76, 3.92, 4.08, 4.24, 4.4 , 4.56, 4.72, 4.88, 5.04, 5.2 , 5.36,
       5.52, 5.68, 5.84, 6.  , 6.16, 6.32, 6.48, 6.64, 6.8 , 6.96, 7.12,
       7.28, 7.44, 7.6 , 7.76, 7.92, 8.08, 8.24, 8.4 , 8.56, 8.72, 8.88,
       9.04, 9.2 , 9.36, 9.52, 9.68, 9.84])

In [ ]:
np.linspace(2,10,10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [ ]:
np.linspace(2.7,10.4)

array([ 2.7       ,  2.85714286,  3.01428571,  3.17142857,  3.32857143,
        3.48571429,  3.64285714,  3.8       ,  3.95714286,  4.11428571,
        4.27142857,  4.42857143,  4.58571429,  4.74285714,  4.9       ,
        5.05714286,  5.21428571,  5.37142857,  5.52857143,  5.68571429,
        5.84285714,  6.        ,  6.15714286,  6.31428571,  6.47142857,
        6.62857143,  6.78571429,  6.94285714,  7.1       ,  7.25714286,
        7.41428571,  7.57142857,  7.72857143,  7.88571429,  8.04285714,
        8.2       ,  8.35714286,  8.51428571,  8.67142857,  8.82857143,
        8.98571429,  9.14285714,  9.3       ,  9.45714286,  9.61428571,
        9.77142857,  9.92857143, 10.08571429, 10.24285714, 10.4       ])

In [ ]:
np.linspace(2.7,10.4).size

50

In [ ]:
np.linspace(2.7,10.4).dtype

dtype('float64')

In [ ]:
np.linspace(2.7,10.4).shape

(50,)

In [ ]:
np.linspace(2.7,10.4).ndim

1

# Shape Manipulation In NumPy.

In [ ]:
import numpy as np

In [ ]:
# .reshape
x = np.array([1,2,3,4])
print(x.shape)
x = x.reshape(2,2)      # Creates a copy of the ndarray.

(4,)


In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
x.reshape(1,1,2,2,1)

array([[[[[1],
          [2]],

         [[3],
          [4]]]]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
# .flatten()
x.flatten()

array([1, 2, 3, 4])

In [ ]:
# .ravel()
x.ravel()

array([1, 2, 3, 4])

In [ ]:
x    # but the value of x is not change.It will remains same.However you cannot assign it to the variable.

array([[1, 2],
       [3, 4]])

In [ ]:
# .resize() -- just like .reshape
# It will same as like .reshape make a copy of an array and .resize changes the value old value of an array.
x.resize(4,1)

In [ ]:
x

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
x.reshape(2,2)        # It will not change it will remaainss constant.
x

array([[1],
       [2],
       [3],
       [4]])

# Stacking.

<font size=3> ***Join a sequence of arrays along a new axis.***

<font size=5> 2D Array.

In [ ]:
# .stack()
# 2D
import numpy as np
n1 = np.array([[1,2,4],
               [5,6,7]])
n2 = np.array([[8,9,10],
               [11,12,13]])
print(f"n1 : \n {n1} \nn2: \n {n2} \n")
print("for axis=0:\n",np.stack((n1,n2),axis=0),"\n") # row-wise stacking.

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2: 
 [[ 8  9 10]
 [11 12 13]] 

for axis=0:
 [[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]] 



In [ ]:
print(f"n1 : \n {n1} \nn2: \n {n2} \n")
print("for axis=1:\n",np.stack((n1,n2),axis=1))  # column-wise stacking.

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2: 
 [[ 8  9 10]
 [11 12 13]] 

for axis=1:
 [[[ 1  2  4]
  [ 8  9 10]]

 [[ 5  6  7]
  [11 12 13]]]


<font size=5> 1D Array.



In [ ]:
# .stack()
# 1D
import numpy as np
n1 = np.array([1,2,3,4])
n2 = np.array([7,8,9,2])

print(f"n1: \n {n1} \nn2: \n {n2} \n")
print("for axis=0:\n",np.stack((n1,n2),axis=0),"\n") # Row-wise Stacking.

n1: 
 [1 2 3 4] 
n2: 
 [7 8 9 2] 

for axis=0:
 [[1 2 3 4]
 [7 8 9 2]] 



In [ ]:
print(f"n1: \n {n1} \nn2: \n {n2} \n")
print("for axis=1:\n",np.stack((n1,n2),axis=1),"\n")  # column-wise Stacking.

n1: 
 [1 2 3 4] 
n2: 
 [7 8 9 2] 

for axis=1:
 [[1 7]
 [2 8]
 [3 9]
 [4 2]] 



# Concatenating.

<font size=3> ***Join a sequence of arrays along an existing axis.***

<font size=5> 2D Array.

In [ ]:
# 2D
import numpy as np
x = np.array([[1,2,3],
              [4,5,6]])
y = np.array([[7,8,9],
              [10,11,12]])

print(f"x : \n {x} \ny: \n {y} \n")
print("Resulting array:\n",np.concatenate((x,y),axis=0))  # row-wise concatenation.

x : 
 [[1 2 3]
 [4 5 6]] 
y: 
 [[ 7  8  9]
 [10 11 12]] 

Resulting array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(f"x : \n {x} \ny: \n {y} \n")
print("Resulting array:\n",np.concatenate((x,y),axis=1))  # column-wise concatenation.

x : 
 [[1 2 3]
 [4 5 6]] 
y: 
 [[ 7  8  9]
 [10 11 12]] 

Resulting array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


<font size=5> 1D Array.

In [ ]:
# 1D
import numpy as np
n1 = ([1,2,3,4])
n2 = ([5,6,7,8])
print(f"n1 : \n {n1} \nn2: \n {n2}  \n")
print("for axis=0:\n",np.concatenate((n1,n2),axis=0),"\n")

n1 : 
 [1, 2, 3, 4] 
n2: 
 [5, 6, 7, 8]  

for axis=0:
 [1 2 3 4 5 6 7 8] 



In [ ]:
print(f"n1 : \n {n1} \nn2: \n {n2}  \n")
print("for axis=1:\n",np.concatenate((n1,n2),axis=1),"\n")

n1 : 
 [1, 2, 3, 4] 
n2: 
 [5, 6, 7, 8]  



AxisError: ignored

# hstack and vstack.

In [ ]:
# 2D array.
import numpy as np
x = np.array([[1,2,3],
              [4,5,6]])
y = np.array([[7,8,9],
              [10,11,12]])

In [ ]:
np.hstack((x,y))  # np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.vstack((x,y))  # np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# 1D array.
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])

In [ ]:
np.hstack((n1,n2))  # np.concatenate((n1,n2),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack((n1,n2))  # np.stack((n1,n2),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Indexing,Slicing & Striding.

In [ ]:
import numpy as np

In [ ]:
# 1D
# (AXIS 0,)
# (COLUMN,)
# (0D,)
x = np.array([1,2,3,4])
print(x[3])
print(x[0])

4
1


In [ ]:
# 2D
# (AXIS 0,AXIS 1)
# (ROWS , COLUMNS)
# (1D, 0D)
x = np.array([[1,2,3,4],
              [5,6,7,8]])
x[0,1] # prefeered way.]

2

In [ ]:
x[0][1] # alternative way.

2

In [ ]:
x[-2,-3]

2

In [ ]:
import numpy as np

In [ ]:
# 3D
# (AXIS 0,AXIS 1,AXIS 2)
# (2D , 1D, 0D)
x = np.array([[[1,2,3,4],
               [5,6,7,8]],
              [[9,10,11,12],
               [13,14,15,16]]])
x[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
x[0,0]

array([1, 2, 3, 4])

In [ ]:
x[0,0,0]

1

In [ ]:
x[1,0,2]

11

In [ ]:
x[1,1,1]

14

- Striding.

  Start(inclusive):stop(exclusive):step

In [ ]:
# 1D
x = np.array([1,2,3,4])
x[0:4:2]

array([1, 3])

In [ ]:
# 2D
y = np.array([[1,2,3,4],
              [5,6,7,8],
              [4,2,5,6],
              [2,5,3,6]])
y[::2]

array([[1, 2, 3, 4],
       [4, 2, 5, 6]])

In [ ]:
y[::3]

array([[1, 2, 3, 4],
       [2, 5, 3, 6]])

In [ ]:
y[::4]

array([[1, 2, 3, 4]])

In [ ]:
y[::1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 2, 5, 6],
       [2, 5, 3, 6]])

In [ ]:
y[::]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 2, 5, 6],
       [2, 5, 3, 6]])

In [ ]:
y[::-2]

array([[2, 5, 3, 6],
       [5, 6, 7, 8]])

In [ ]:
r = np.array([[[1,2,3,4],
               [4,5,6,7],
               [2,3,1,4],
               [6,5,3,4]]])

In [ ]:
r[1:3,1:3]

array([], shape=(0, 2, 4), dtype=int64)

In [ ]:
r[::1]

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [2, 3, 1, 4],
        [6, 5, 3, 4]]])

- Slicing.

In [ ]:
# 2D
x = np.array([[1,2,3]
              [4,5,6]])
x[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
x[0:2,0]

array([1, 4])

In [ ]:
x[:,1]

array([2, 5])

In [ ]:
x[:,0]

array([1, 4])

In [ ]:
x[::,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [-1,-2,-3,-4]])

In [ ]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [-1, -2, -3, -4]])

In [ ]:
x[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
x[3,1:3]

array([-2, -3])

In [ ]:
x[3,3]

-4

In [ ]:
x[1:3,3]

array([ 8, 12])

In [ ]:
x[1:3,0]

array([5, 9])

In [ ]:
# 3D
y = np.array([[[1,2],
               [3,4],
               [5,6]],
              [[7,8],
               [9,10],
               [11,12]]])

In [ ]:
y

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
y[0,0:2,0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
y[1,0:2,0:2]

array([[ 7,  8],
       [ 9, 10]])

# Arithmetic with NumPy.

- ***Any operation between equal-size arrays happens element-wise.***

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,3,4],
              [5,6,7]])
(a+b)     # adding an arrays element-wise.

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [ ]:
(a*b)     # Multiplying an arrays element-wise.

array([[ 2,  6, 12],
       [20, 30, 42]])

In [ ]:
(a-b)     # Subtracting an arrays element-wise.

array([[-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
(a/b)     # Dividing an arrays element-wise.

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286]])

In [ ]:
b-a

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
b/a

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667]])

Arithmetic operations with scalars propogate the scalar argument to each element in the array.

Operattions Between differently sized arrays is called broadcasting.

In [ ]:
(a*2)    # Broadcasting.

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
(b*3)

array([[ 6,  9, 12],
       [15, 18, 21]])

In [ ]:
(a-2)

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
(b+4)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

# Universal Function.

A universal function, or ufunc, is a function that perform element-wise operations on data in ndarrays.

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.add(a,b)  # or a+b

array([ 6,  8, 10, 12])

In [ ]:
np.subtract(b,a)  # or b-a

array([4, 4, 4, 4])

In [ ]:
np.multiply(a,b)  # or a*b

array([ 5, 12, 21, 32])

In [ ]:
np.divide(a,b)  # or a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.sqrt(b)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

# Pseudo-Random Number Generation.

In [ ]:
# In python we have a built-in module random.
import random

random.random()

0.7525797199284837

In [ ]:
random.seed(2)   # Same seed value will generate the same random no.
random.random()

0.9560342718892494

In [ ]:
np.random.random(2)
np.random.random()

0.649611857520865